language: ruby
rvm:
  - 2.2
  - 2.5.3
before_install:
  - openssl aes-256-cbc -K $encrypted_d9db0aa29b2e_key -iv $encrypted_d9db0aa29b2e_iv -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar
  - gem install bundler --version '1.11.2'
